#vanaurum_project/data_settings.py

#This file contains all of the data related settings and is imported by the master settings.py file.


ASSET_LIST=[
            'PALLADIUM_D',
            'PLATINUM_D',
            'ALUMINUM_D',
            'GOLD_D',
            'SILVER_D',
            'USD_D',
            'SPX_D',
            'VIX_D',
            'UST10Y_D',
            'UST2Y_D',
            'UST5Y_D',
            'UST30Y_D',
            'FEDFUNDS_30_D',
            'CORN_D',
            'DJIA_D',
            'OATS_D',
            'ROUGH_RICE_D',
            'SOYBEANS_D',
            'WHEAT_D',
            'AUD_D',
            'GBP_D',
            'CAD_D',
            'EURO_FX_D',
            'EURODOLLAR_D',
            'JPY_D',
            'LEAN_HOGS_D',
            'LIVE_CATTLE_D',
            'MEXICAN_PESO_D',
            'NASDAQ100_D',
            'NZD_D',
            'NIKKEI225_D',
            'CHF_D',
            'COPPER_D',
            'RUSSEL2000_D',
            'RUSSEL1000_D',
            'EURO_STOXX_50_D',
            'COFFEE_D',
            'COTTON_D',
            'GASOIL_D',
            'HEATING_OIL_D',
            'ORANGE_JUICE_D',
            'SUGAR_D',
            'NATURAL_GAS_D',
            'WTI_CRUDE_OIL_D',
            'FTSE100_D',
            'TSX60_D',
            'GASOLINE_D',
            'BITCOIN_USD_D',
            'ETHEREUM_USD_D',
            'GDX_D',
            'GDXJ_D',
            'VWO_D',
            'FXI_D',
            'VCR_D',
            'VDC_D',
            'VPU_D',
            'XLF_D',
            'VIS_D',  
            'VHT_D',
            'VNQ_D', 
            'VOX_D',
            'IBB_D',
            'SIL_D',
            'RSX_D',
            'PLND_D',
            'VNM_D',
            'ISRA_D',    
            'LIT_D',
            'VDE_D',
            'EWL_D',  
            'EWI_D',
            'XOP_D',
            'HYG_D',
            'EFA_D',
            'EEM_D',
            'TLT_D',
            'IYT_D',
            ]


FUTURES_TAG_LIST={
             'GOLD_D': "CME_GC1_ON",
             'SILVER_D': "CME_SI1_ON",
             'PALLADIUM_D': "CME_PA1_OF",
             'PLATINUM_D':"CME_PL1_ON",
             'ALUMINUM_D':"SHFE_AL1_ON",
             'USD_D': "ICE_DX1_OB",
             'SPX_D': "CME_SP1_EB",
             'VIX_D': "CBOE_VX1_ER",
             'UST10Y_D':"CME_TY1_ON",
             'UST2Y_D':"CME_TU1_FB",
             'UST5Y_D':"CME_FV1_OF",
             'UST30Y_D':"CME_US1_ON",
             'FEDFUNDS_30_D':"CME_FF1_ON",
             'CORN_D':"CME_C1_ON",
             'DJIA_D':"CME_YM1_ON",
             'OATS_D':"CME_O1_ON",
             'ROUGH_RICE_D':"CME_RR1_ON",
             'SOYBEANS_D':"CME_S1_ON",
             'WHEAT_D':"CME_W1_ON",
             'AUD_D':"CME_AD1_ON",
             'GBP_D':"CME_BP1_ON",
             'CAD_D':"CME_CD1_ON",
             'EURO_FX_D':"CME_EC1_ON",
             'EURODOLLAR_D':"CME_ED1_ON",
             'JPY_D':"CME_JY1_ON",
             'LEAN_HOGS_D':"CME_LN1_ON",
             'LIVE_CATTLE_D':"CME_LC1_ON",
             'MEXICAN_PESO_D':"CME_MP1_ON",
             'NASDAQ100_D':"CME_NQ1_ON",
             'NZD_D':"CME_NE1_ON",
             'NIKKEI225_D':"CME_NK1_ON",
             'CHF_D':"CME_SF1_ON",
             'COPPER_D': "CME_HG1_ON",
             'RUSSEL2000_D':"ICE_TF1_ON",
             'RUSSEL1000_D':"ICE_RF1_ON",
             'EURO_STOXX_50_D':"EUREX_FESX1_ON",
             'COFFEE_D':"ICE_KC1_ON",
             'COTTON_D':"ICE_CT1_ON",
             'GASOIL_D':"ICE_G1_ON",
             'HEATING_OIL_D':"CME_HO1_ON",
             'ORANGE_JUICE_D':"ICE_OJ1_ON",
             'SUGAR_D':"ICE_SB1_ON",
             'NATURAL_GAS_D':"CME_NG1_ON",
             'WTI_CRUDE_OIL_D':"CME_CL1_ON",
             'FTSE100_D':"LIFFE_Z1_ON",
             'TSX60_D':"MX_SXF1_ON",
             'GASOLINE_D':"CME_RB1_ON",
             'BITCOIN_USD_D':"BITFINEX/BTCUSD",
             'ETHEREUM_USD_D':"BITFINEX/ETHUSD",
             'GDX_D':"EOD/GDX",
             'GDXJ_D':"EOD/GDXJ",
             'VWO_D':"EOD/VWO",
             'FXI_D':"EOD/FXI",
             'VCR_D':"EOD/VCR",
             'VDC_D':"EOD/VDC",
             'VPU_D':"EOD/VPU",
             'XLF_D':"EOD/XLF",
             'VIS_D':"EOD/VIS",  
             'VHT_D':"EOD/VHT",
             'VNQ_D':"EOD/VNQ", 
             'VOX_D':"EOD/VOX",
             'IBB_D':"EOD/IBB",
             'SIL_D':"EOD/SIL",
             'RSX_D':"EOD/RSX",
             'ISRA_D':"EOD/ISRA",
             'VNM_D':"EOD/VNM",
             'PLND_D':"EOD/PLND",  
             'LIT_D':"EOD/LIT",
             'VDE_D':"EOD/VDE",
             'EWL_D':"EOD/EWL",
             'EWI_D':"EOD/EWI",
             'XOP_D':"EOD/XOP",
             'HYG_D':"EOD/HYG",
             'EFA_D':"EOD/EFA",  
             'EEM_D':"EOD/EEM",
             'TLT_D':"EOD/TLT",
             'IYT_D':"EOD/IYT",         
            }            

COT_FUTURES_LIST=[
            'SILVER_COT_FO',
            'GOLD_COT_FO',
            'COPPER_COT_FO',
            'CORN_COT_FO',
            'COTTON_COT_FO',
            #'DJIA_COT_FO',
            #'E-MINI_MSCI_EMERGING_MARKETS_COT_FO',
            'E-MINI_RUSSELL_2000_COT_FO',
            'E-MINI_SPX_500_COT_FO',
            'FRZN_CONCENTRATED_ORANGE_JUICE_COT_FO',
            #'10YR_3MO_INTEREST_RATE_SWAPS_COT_FO',
            #'BLOOMBERG_COMMODITY_INDEX_COT_FO',
            #'CANADIAN_HEAVY_CRUDE_COT_FO',
            'CANADIAN_DOLLAR_COT_FO',
            'JAPANESE_YEN_COT_FO',
            'LIVE_CATTLE_COT_FO',
            'SOY_BEANS_COT_FO',
            'NASDAQ_100_COT_FO',
            'US_TREASURY_BONDS_COT_FO',
            'VIX_COT_FO',
            'PLATINUM_COT_FO',
            'PALLADIUM_COT_FO'  
            ]

COT_TAG_CONV_LIST={
            'SILVER_COT_FO': "084691_FO_ALL",
            'GOLD_COT_FO': "088691_FO_ALL",
            'COPPER_COT_FO': "085692_FO_ALL",
            'CORN_COT_FO': "002602_FO_ALL",
            'COTTON_COT_FO':"033661_FO_ALL",
            'DJIA_COT_FO':"124601_FO_ALL",
            'E-MINI_MSCI_EMERGING_MARKETS_COT_FO':"244742_FO_ALL",
            'E-MINI_RUSSELL_2000_COT_FO':"239742_FO_ALL",
            'E-MINI_SPX_500_COT_FO':"13874A_FO_ALL",
            'FRZN_CONCENTRATED_ORANGE_JUICE_COT_FO':"040701_FO_ALL",
            #'BLOOMBERG_COMMODITY_INDEX_COT_FO':"221602_F_ALL",
            'CANADIAN_DOLLAR_COT_FO':"090741_FO_ALL",
            #'CANADIAN_HEAVY_CRUDE_COT_FO':"067A49_FO_ALL",
            '10YR_3MO_INTEREST_RATE_SWAPS_COT_FO':"246602_FO_ALL",
            'JAPANESE_YEN_COT_FO':"097741_FO_ALL",
            'LIVE_CATTLE_COT_FO':"057642_FO_ALL",
            'SOY_BEANS_COT_FO':"005603_FO_ALL",
            'NASDAQ_100_COT_FO':"209742_FO_ALL",
            'US_TREASURY_BONDS_COT_FO':"020601_FO_ALL",
            'VIX_COT_FO':"1170E1_FO_ALL",
            'PLATINUM_COT_FO':"076651_FO_ALL",
            'PALLADIUM_COT_FO':"075651_FO_ALL",
            }
          

COT_ASSET_LIB={
            'SILVER_COT_FO': "SILVER_D",
            'GOLD_COT_FO': "GOLD_D",
            'COPPER_COT_FO': "COPPER_D",
            'CORN_COT_FO': "CORN_D",
            'COTTON_COT_FO':"COTTON_D",
            'DJIA_COT_FO':"DJIA_D",
            'E-MINI_MSCI_EMERGING_MARKETS_COT_FO':"VWO_D",
            'E-MINI_RUSSELL_2000_COT_FO':"RUSSEL2000_D",
            'E-MINI_SPX_500_COT_FO':"SPX_D",
            'FRZN_CONCENTRATED_ORANGE_JUICE_COT_FO':"ORANGE_JUICE_D",
            'JAPANESE_YEN_COT_FO':"JPY_D",
            'LIVE_CATTLE_COT_FO':"LIVE_CATTLE_D",
            'SOY_BEANS_COT_FO':"SOYBEANS_D",
            'NASDAQ_100_COT_FO':"NASDAQ100_D",
            'US_TREASURY_BONDS_COT_FO':"UST10Y_D",
            'VIX_COT_FO':"VIX_D",
            'PLATINUM_COT_FO':"PLATINUM_D",
            'PALLADIUM_COT_FO':"PALLADIUM_D",
            'CANADIAN_DOLLAR_COT_FO':"CAD_D",
            }

RATIOS=[
    {'tag':'RATIO_GOLD_SILVER_D', 'numerator':'GOLD_D', 'denominator':'SILVER_D'},
    {'tag':'RATIO_COPPER_GOLD_D', 'numerator':'COPPER_D', 'denominator':'GOLD_D'},
    {'tag':'RATIO_GOLD_WTI_D', 'numerator':'COPPER_D', 'denominator':'WTI_CRUDE_OIL_D'},
    {'tag':'RATIO_SPX_GOLD_D', 'numerator':'SPX_D', 'denominator':'GOLD_D'},
    {'tag':'RATIO_GDX_GOLD_D', 'numerator':'GDX_D', 'denominator':'GOLD_D'},
    {'tag':'RATIO_SIL_SILVER_D', 'numerator':'SIL_D', 'denominator':'SILVER_D'},
    {'tag':'RATIO_VDE_SPX_D', 'numerator':'VDE_D', 'denominator':'SPX_D'},
    {'tag':'RATIO_GDX_SPX_D', 'numerator':'GDX_D', 'denominator':'SPX_D'},
    {'tag':'RATIO_IBB_SPX_D', 'numerator':'IBB_D', 'denominator':'SPX_D'},
    {'tag':'RATIO_FXI_SPX_D', 'numerator':'FXI_D', 'denominator':'SPX_D'},
    {'tag':'RATIO_RSX_SPX_D', 'numerator':'RSX_D', 'denominator':'SPX_D'},
    {'tag':'RATIO_GOLD_UST10Y_D', 'numerator':'GOLD_D', 'denominator':'UST10Y_D'},
    {'tag':'RATIO_SPX_UST10Y_D', 'numerator':'SPX_D', 'denominator':'UST10Y_D'},
    {'tag':'RATIO_PLAT_GOLD_D', 'numerator':'PLATINUM_D', 'denominator':'GOLD_D'},
    {'tag':'RATIO_PLAT_SILVER_D', 'numerator':'PLATINUM_D', 'denominator':'SILVER_D'},
    {'tag':'RATIO_PLAT_COPPER_D', 'numerator':'PLATINUM_D', 'denominator':'COPPER_D'},
    {'tag':'RATIO_VDE_WTICRUDE_D', 'numerator':'VDE_D', 'denominator':'WTI_CRUDE_OIL_D'},
    {'tag':'RATIO_HYG_WTICRUDE_D', 'numerator':'HYG_D', 'denominator':'WTI_CRUDE_OIL_D'},
    {'tag':'RATIO_HYG_GASOLINE_D', 'numerator':'HYG_D', 'denominator':'GASOLINE_D'},
    {'tag':'RATIO_TLT_WTICRUDE_D', 'numerator':'TLT_D', 'denominator':'WTI_CRUDE_OIL_D'},
    {'tag':'RATIO_IYT_DJIA_D', 'numerator':'IYT_D', 'denominator':'DJIA_D'},
]                        

#Assets that shouldn't appear in VaiSi related analytixs
VAISI_EXCLUSIONS=[
    'YC2YR',
    'PESPX',
    'UST2Y',
    'UST5Y',
    'EURODOLLAR',
    'FEDFUNDS_30',
    'VAISI_DATA',
    ]
  

#Tables with the '_D' suffix that shouldn't appear in DBquery primary asset list.
PRIMARY_ASSET_EXCLUSIONS=[
                        'US1MO_TREASURY_YIELD_D',
                        'US2MO_TREASURY_YIELD_D',
                        'US3MO_TREASURY_YIELD_D',
                        'US6MO_TREASURY_YIELD_D',
                        'US1YR_TREASURY_YIELD_D',
                        'US2YR_TREASURY_YIELD_D',
                        'US3YR_TREASURY_YIELD_D',
                        'US5YR_TREASURY_YIELD_D',
                        'US7YR_TREASURY_YIELD_D',
                        'US10YR_TREASURY_YIELD_D',
                        'US20YR_TREASURY_YIELD_D',
                        'US30YR_TREASURY_YIELD_D',
                        'US_INFLATION_YOY_D',
                        'US_HY_CREDIT_YIELD_D',
                        'EM_HY_CREDIT_YIELD_D',
                        'YC10Y5Y_D',
                        'YC10Y2Y_D',
                        'YC10Y3MO_D',
                        'YC5Y1Y_D',
                        'YC1Y1MO_D',
                        'US1MO_TREASURY_REAL_YIELD_D',
                        'US3MO_TREASURY_REAL_YIELD_D',
                        'US6MO_TREASURY_REAL_YIELD_D',
                        'US1YR_TREASURY_REAL_YIELD_D',
                        'US2YR_TREASURY_REAL_YIELD_D',
                        'US3YR_TREASURY_REAL_YIELD_D',
                        'US5YR_TREASURY_REAL_YIELD_D',
                        'US7YR_TREASURY_REAL_YIELD_D',
                        'US10YR_TREASURY_REAL_YIELD_D',
                        'US20YR_TREASURY_REAL_YIELD_D',
                        'US30YR_TREASURY_REAL_YIELD_D']                  




AMBIGUOUS_COT_LIST=['COTTON',]

##### Natural Language Description Date ######

#NL expressions for the primary asset choice box.
NL_ASSET_LIST={
             'GOLD_D': "Gold ",
             'SILVER_D': "Silver ",
             'PALLADIUM_D': "Palladium ",
             'PLATINUM_D':"Platinum ",
             'ALUMINUM_D':"Aluminum ",
             'USD_D': "the US Dollar ",
             'SPX_D': "the S&P 500 Index ",
             'VIX_D': "the VIX ",
             'UST10Y_D':"10-Year US Treasuries ",
             'UST2Y_D':"2-Year US Treasuries ",
             'UST5Y_D':"5-Year US Treasuries ",
             'UST30Y_D':"30-Year US Treasuries ",
             'FEDFUNDS_30_D':"the 30-Day Fed Funds Rate ",
             'CORN_D':"Corn ",
             'DJIA_D':"the Down Jones Industrial Average ",
             'OATS_D':"Oat futures ",
             'ROUGH_RICE_D':"Rough Rice futures ",
             'SOYBEANS_D':"Soybean futures ",
             'WHEAT_D':"Wheat futures ",
             'AUD_D':"the Australian Dollar ",
             'GBP_D':"the British Pound ",
             'CAD_D':"the Canadian Dollar ",
             'EURO_FX_D':"Euro FX ",
             'EURODOLLAR_D':"Eurodollar futures ",
             'JPY_D':"the Japanese Yen ",
             'LEAN_HOGS_D':"Lean Hog futures ",
             'LIVE_CATTLE_D':"Live cattle futures ",
             'MEXICAN_PESO_D':"Mexican Peso ",
             'NASDAQ100_D':"the Nasdaq 100 Index ",
             'NZD_D':"the New Zealand Dollar ",
             'NIKKEI225_D':"the Nikkei 225 Index ",
             'CHF_D':"the Swiss Franc ",
             'COPPER_D': "Copper ",
             'RUSSEL2000_D':"the Russell 2000 Index ",
             'RUSSEL1000_D':"the Russell 1000 Index ",
             'EURO_STOXX_50_D':"the Euro Stoxx 50 Index ",
             'COFFEE_D':"Coffee futures ",
             'COTTON_D':"Cotton futures ",
             'GASOIL_D':"Gasoil futures ",
             'HEATING_OIL_D':"Heating Oil futures ",
             'ORANGE_JUICE_D':"Orange Juice futures ",
             'SUGAR_D':"Sugar futures ",
             'NATURAL_GAS_D':"Natural Gas futures ",
             'WTI_CRUDE_OIL_D':"WTI Crude Oil futures ",
             'FTSE100_D':"the FTSE 100 Index ",
             'TSX60_D':"the TSX 60 Index ",
             'GASOLINE_D':"Gasoline futures ",
             'BITCOIN_USD_D':"Bitcoin ($USD) ",
             'ETHEREUM_USD_D':"Etherium ($USD) ",
             'US1MO_TREASURY_YIELD_D': "1-month US treasury yields ",
             'US2MO_TREASURY_YIELD_D': "2-month US treasury yields ",
             'US3MO_TREASURY_YIELD_D': "3-month US treasury yields ",
             'US6MO_TREASURY_YIELD_D': "6-month US treasury yields ",
             'US1YR_TREASURY_YIELD_D': "1-year US treasury yields ",
             'US2YR_TREASURY_YIELD_D': "2-year US treasury yields ",
             'US3YR_TREASURY_YIELD_D': "3-year US treasury yields ",
             'US5YR_TREASURY_YIELD_D': "5-year US treasury yields ",
             'US7YR_TREASURY_YIELD_D': "7-year US treasury yields ",
             'US10YR_TREASURY_YIELD_D': "10-year US treasury yields ",
             'US20YR_TREASURY_YIELD_D': "20-year US treasury yields ",
             'US30YR_TREASURY_YIELD_D': "30-year US treasury yields ",
             'US_INFLATION_YOY_D': "year-over-year US CPI inflation ",
             'US_HY_CREDIT_YIELD_D': "high yield US corporate bond yields ",
             'EM_HY_CREDIT_YIELD_D': "emerging market high yield credit yields ",
             'YC10Y5Y_D': "the 10-year to 5-year US treasury yield spread ",
             'YC10Y2Y_D': "the 10-year to 2-year US treasury yield spread ",
             'YC10Y3MO_D': "the 10-year to 3-month US treasury yield spread ",
             'YC5Y1Y_D': "the 5-year to 1-year US treasury yield spread ",
             'YC1Y1MO_D': "the 1-year to 1-month US treasury yield spread ",
             'US1MO_TREASURY_REAL_YIELD_D': "the 1-month inflation-adjusted US treasury yield ",
             'US3MO_TREASURY_REAL_YIELD_D': "the 3-month inflation-adjusted US treasury yield ",
             'US6MO_TREASURY_REAL_YIELD_D': "the 6-month inflation-adjusted US treasury yield ",
             'US1YR_TREASURY_REAL_YIELD_D': "the 1-year inflation-adjusted US treasury yield ",
             'US2YR_TREASURY_REAL_YIELD_D': "the 2-year inflation-adjusted US treasury yield ",
             'US3YR_TREASURY_REAL_YIELD_D': "the 3-year inflation-adjusted US treasury yield ",
             'US5YR_TREASURY_REAL_YIELD_D': "the 5-year inflation-adjusted US treasury yield ",
             'US7YR_TREASURY_REAL_YIELD_D': "the 7-year inflation-adjusted US treasury yield ",
             'US10YR_TREASURY_REAL_YIELD_D': "the 10-year inflation-adjusted US treasury yield ",
             'US20YR_TREASURY_REAL_YIELD_D': "the 20-year inflation-adjusted US treasury yield ",
             'US30YR_TREASURY_REAL_YIELD_D': "the 30-year inflation-adjusted US treasury yield ",
             'GDX_D':"the VanEck senior gold miners ETF (GDX) ",
             'GDXJ_D': "the VanEck junior gold miners ETF (GDXJ) ",
             'VWO_D':"the Vanguard emerging markets stock index ETF (VWO) ",
             'FXI_D':"the iShares China large cap ETF (FXI) ",  
             'VCR_D':"the Vanguard consumer discretionary sector ETF ",
             'VDC_D':"the Vanguard consumer staples sector ETF ",
             'VPU_D':"the Vanguard electric utilities sector ETF ",
             'XLF_D':"the SPDR financial sector ETF ",
             'VIS_D':"the Vanguard industrial sector ETF ",  
             'VHT_D':"the Vanguard health care sector ETF ",
             'VNQ_D':"the Vanguard real estate sector ETF ", 
             'VOX_D':"the Vanguard telecommunications sector ETF ",
             'IBB_D':"the iShares Nasdaq Biotechnology sector ETF ",
             'SIL_D':"the GlobalX Funds Silver Miner ETF ",  
             'RATIO_GOLD_SILVER_D': 'the Gold-Silver ratio ',
             'RATIO_COPPER_GOLD_D': 'the Copper-Gold ratio ',
             'RATIO_GOLD_WTI_D': 'the Gold-WTI Crude Oil ratio ',
             'RATIO_SPX_GOLD_D': 'the S&P500-Gold Ratio ',
             'RATIO_GDX_GOLD_D': 'the GDX-Gold Ratio ',
             'RATIO_SIL_SILVER_D': 'the SIL to Silver ratio ',
             'RATIO_VDE_SPX_D': 'the Energy Sector to S&P500 ratio ',
             'RATIO_GDX_SPX_D': 'the Senior Gold Mining Sector to S&P500 ratio ',
             'RATIO_IBB_SPX_D': 'the Biotechnology Sector to S&P500 ratio ',
             'RATIO_FXI_SPX_D': 'the Chinese Stock Index to S&P500 ratio ',
             'RATIO_RSX_SPX_D': 'the Russia Stock Index to S&P500 ratio ',
             'RATIO_HYG_WTICRUDE_D':'the High Yield Corporate Credit to WTI Crude Oil ratio ',
             'RATIO_HYG_GASOLINE_D':'the High Yield Corporate Credit to Gasoline ratio ',
             'RATIO_TLT_WTICRUDE_D':'the 20+ Year Treasury Bond to WTI Crude Oil ratio ',
             'RATIO_GOLD_UST10Y_D': 'the Gold to 10-Year US treasury ratio ',
             'RATIO_SPX_UST10Y_D': 'the S&P500 to 10-Year US treasury ratio ',
             'RATIO_PLAT_GOLD_D': "the Platinum to Gold ratio ",
             'RATIO_PLAT_SILVER_D': "the Platinum to Silver ratio ",
             'RATIO_PLAT_COPPER_D': "the Platinum to Copper ratio ",
             'RATIO_VDE_WTICRUDE_D': "the VDE Energy ETF to WTI Crude Oil ratio ",
             'RATIO_IYT_DJIA_D':"the Dow Transports to Dow Industrial Average ratio ",
             'RSX_D':'the VanEck Russian stock market index ETF ',
             'ISRA_D':'the VanEck Israeli stock market index ETF ',
             'VNM_D':'the VanEck Vietnam stock market index ETF ',
             'PLND_D':'the VanEck Poland stock market index ETF ', 
             'LIT_D': 'the GlobalX Lithium and battery technology stock ETF ',
             'VDE_D': 'the Vanguard energy sector ETF ',
             'EWL_D': 'the MSCI iShares Switzerland ETF ',  
             'EWI_D': 'the MSCI iShares Italy ETF ',   
             'XOP_D':"the SPDR S&P Oil & Gas Explorers ETF ",
             'HYG_D':"the iShares High Yield Corporate Bond ETF ",
             'EFA_D':"iShares MSCI EAFE Index Fund ETF ",  
             'EEM_D':"iShares MSCI Emerging Markets ETF ", 
             'TLT_D':"iShares 20+ Year Treasury Bond ETF ",
             'IYT_D':"iShares Dow Jones Transportation ETF ",
            }


#NL expressions for the primary comparison asset box.
NL_COMPARATOR_LIB={
             'GOLD_D': "Gold's ",
             'SILVER_D': "Silver's ",
             'PALLADIUM_D': "Palladium's ",
             'PLATINUM_D':"Platinum's ",
             'ALUMINUM_D':"Aluminum's ",
             'USD_D': "the US Dollar's ",
             'SPX_D': "the S&P 500 Index ",
             'VIX_D': "the VIX's ",
             'UST10Y_D':"the 10-Year US Treasuries ",
             'UST2Y_D':"the 2-Year US Treasuries ",
             'UST5Y_D':"the 5-Year US Treasuries ",
             'UST30Y_D':"the 30-Year US Treasuries ",
             'FEDFUNDS_30_D':"the 30-Day Fed Funds Rate's ",
             'CORN_D':"Corn's ",
             'DJIA_D':"the Down Jones Industrial Average's ",
             'OATS_D':"the Oat futures ",
             'ROUGH_RICE_D':"the Rough Rice futures ",
             'SOYBEANS_D':"the Soybean futures ",
             'WHEAT_D':"the Wheat futures ",
             'AUD_D':"the Australian Dollar's ",
             'GBP_D':"the British Pound's ",
             'CAD_D':"the Canadian Dollar's ",
             'EURO_FX_D':"the Euro FX ",
             'EURODOLLAR_D':"the Eurodollar futures ",
             'JPY_D':"the Japanese Yen's ",
             'LEAN_HOGS_D':"the Lean Hog futures ",
             'LIVE_CATTLE_D':"the Live cattle futures ",
             'MEXICAN_PESO_D':"the Mexican Peso's ",
             'NASDAQ100_D':"the Nasdaq 100 Index's ",
             'NZD_D':"the New Zealand Dollar's ",
             'NIKKEI225_D':"the Nikkei 225 Index's ",
             'CHF_D':"the Swiss Franc's ",
             'COPPER_D': "Copper's ",
             'RUSSEL2000_D':"the Russell 2000 Index's ",
             'RUSSEL1000_D':"the Russell 1000 Index's ",
             'EURO_STOXX_50_D':"the Euro Stoxx 50 Index ",
             'COFFEE_D':"Coffee futures' ",
             'COTTON_D':"Cotton futures' ",
             'GASOIL_D':"Gasoil futures' ",
             'HEATING_OIL_D':"Heating Oil futures' ",
             'ORANGE_JUICE_D':"Orange Juice futures' ",
             'SUGAR_D':"Sugar futures' ",
             'NATURAL_GAS_D':"Natural Gas futures' ",
             'WTI_CRUDE_OIL_D':"WTI Crude Oil futures' ",
             'FTSE100_D':"the FTSE 100 Index's ",
             'TSX60_D':"the TSX 60 Index's ",
             'GASOLINE_D':"Gasoline futures' ",
             'BITCOIN_USD_D':"Bitcoin's ($USD) ",
             'ETHEREUM_USD_D':"Etherium's ($USD) ",
             'CANADIAN_DOLLAR_COT_FO':"the Canadian Dollar committment of traders report ",
             'SILVER_COT_FO': "the Silver committment of traders report ",
             'GOLD_COT_FO': "the Gold committment of traders report ",
             'COPPER_COT_FO': "the Copper committment of traders report ",
             'CORN_COT_FO': "the Corn committment of traders report ",
             'COTTON_COT_FO':"the Cotton committment of traders report ",
             'DJIA_COT_FO':"the Dow Jones Industrial Average committment of traders report ",
             'E-MINI_MSCI_EMERGING_MARKETS_COT_FO':"the E-mini MSCI Emerging Markets committment of traders report ",
             'E-MINI_RUSSELL_2000_COT_FO':"the E-mini Russell 2000 Index committment of traders report ",
             'E-MINI_SPX_500_COT_FO':"E-mini S&P500 committment of traders report ",
             'FRZN_CONCENTRATED_ORANGE_JUICE_COT_FO':"the frozen orange juice committment of traders report ",
             '10YR_3MO_INTEREST_RATE_SWAPS_COT_FO':"10-Year / 3- Month interest rate swap committment of traders report ",
             'JAPANESE_YEN_COT_FO':"the Japanese Yen committment of traders report ",
             'LIVE_CATTLE_COT_FO':"the live cattle committment of traders report ",
             'SOY_BEANS_COT_FO':"the soybeans committment of traders report ",
             'NASDAQ_100_COT_FO':"the Nasdaq 100 index committment of traders report ",
             'US_TREASURY_BONDS_COT_FO':"the US Treasury Bond committment of traders report ",
             'VIX_COT_FO':"the Vix committment of traders report ",
             'PLATINUM_COT_FO':"the Platinum committment of traders report ",
             'PALLADIUM_COT_FO':"the Palladium committment of traders report ",
             'US1MO_TREASURY_YIELD_D': " the 1-month US treasury yield's ",
             'US2MO_TREASURY_YIELD_D': " the 2-month US treasury yield's ",
             'US3MO_TREASURY_YIELD_D': "the 3-month US treasury yield's ",
             'US6MO_TREASURY_YIELD_D': "the 6-month US treasury yield's ",
             'US1YR_TREASURY_YIELD_D': "the 1-year US treasury yield's ",
             'US2YR_TREASURY_YIELD_D': "the 2-year US treasury yield's ",
             'US3YR_TREASURY_YIELD_D': "the 3-year US treasury yield's ",
             'US5YR_TREASURY_YIELD_D': "the 5-year US treasury yield's ",
             'US7YR_TREASURY_YIELD_D': "the 7-year US treasury yield's ",
             'US10YR_TREASURY_YIELD_D': "the 10-year US treasury yield's ",
             'US20YR_TREASURY_YIELD_D': "the 20-year US treasury yield's ",
             'US30YR_TREASURY_YIELD_D': "the 30-year US treasury yield's ",
             'US_INFLATION_YOY_D': "year-over-year US CPI inflation's ",
             'US_HY_CREDIT_YIELD_D': "the high yield US corporate bond yield's ",
             'EM_HY_CREDIT_YIELD_D': "the emerging market high yield credit yield's ",
             'YC10Y5Y_D': "the 10-year to 5-year US treasury yield spread's ",
             'YC10Y2Y_D': "the 10-year to 2-year US treasury yield spread's ",
             'YC10Y3MO_D': "the 10-year to 3-month US treasury yield spread's ",
             'YC5Y1Y_D': "the 5-year to 1-year US treasury yield spread's ",
             'YC1Y1MO_D': "the 1-year to 1-month US treasury yield spread's ",
             'US1MO_TREASURY_REAL_YIELD_D': "the 1-month inflation-adjusted US treasury yield's ",
             'US3MO_TREASURY_REAL_YIELD_D': "the 3-month inflation-adjusted US treasury yield's ",
             'US6MO_TREASURY_REAL_YIELD_D': "the 6-month inflation-adjusted US treasury yield's ",
             'US1YR_TREASURY_REAL_YIELD_D': "the 1-year inflation-adjusted US treasury yield's ",
             'US2YR_TREASURY_REAL_YIELD_D': "the 2-year inflation-adjusted US treasury yield's ",
             'US3YR_TREASURY_REAL_YIELD_D': "the 3-year inflation-adjusted US treasury yield's ",
             'US5YR_TREASURY_REAL_YIELD_D': "the 5-year inflation-adjusted US treasury yield's ",
             'US7YR_TREASURY_REAL_YIELD_D': "the 7-year inflation-adjusted US treasury yield's ",
             'US10YR_TREASURY_REAL_YIELD_D': "the 10-year inflation-adjusted US treasury yield's ",
             'US20YR_TREASURY_REAL_YIELD_D': "the 20-year inflation-adjusted US treasury yield's ",
             'US30YR_TREASURY_REAL_YIELD_D': "the 30-year inflation-adjusted US treasury yield's ",
             'GDX_D':" GDX's ",
             'GDXJ_D':" GDXJ's ",
             'VWO_D':" VWO's ",
             'FXI_D':" FXI's ",
             'PESPX_D':"the S&P500 price to earnings ratio's ",
             'VCR_D':"the Vanguard consumer discretionary sector ETF's ",
             'VDC_D':"the Vanguard consumer staples sector ETF's ",
             'VPU_D':"the Vanguard electric utilities sector ETF's ",
             'XLF_D':"the SPDR financial sector ETF's ",
             'VIS_D':"the Vanguard industrial sector ETF's ",  
             'VHT_D':"the Vanguard health care sector ETF's ",
             'VNQ_D':"the Vanguard real estate sector ETF's ", 
             'VOX_D':"the Vanguard telecommunications sector ETF's ",
             'IBB_D':"the iShares Nasdaq Biotechnology sector ETF's ",
             'SIL_D':"the GlobalX Funds Silver Miner ETF's ",
             'RATIO_GOLD_SILVER_D': "the Gold-Silver ratio's ",
             'RATIO_COPPER_GOLD_D': "the Copper-Gold ratio's ",
             'RATIO_GOLD_WTI_D': "the Gold-WTI Crude Oil ratio's ",
             'RATIO_SPX_GOLD_D': "the S&P500-Gold Ratio's ",
             'RATIO_GDX_GOLD_D': "the GDX-Gold Ratio's ",
             'RATIO_SIL_SILVER_D': "the SIL to Silver ratio's ",
             'RATIO_VDE_SPX_D': "the Energy Sector to S&P500 ratio's ",
             'RATIO_GDX_SPX_D': "the Senior Gold Mining Sector to S&P500 ratio's ",
             'RATIO_IBB_SPX_D': "the Biotechnology Sector to S&P500 ratio's ",
             'RATIO_FXI_SPX_D': "the Chinese Stock Index to S&P500 ratio's ",
             'RATIO_RSX_SPX_D': "the Russia Stock Index to S&P500 ratio's ",
             'RATIO_GOLD_UST10Y_D': "the Gold to 10-Year US treasury ratio's ",
             'RATIO_SPX_UST10Y_D': "the S&P500 to 10-Year US treasury ratio's ", 
             'RATIO_PLAT_GOLD_D': "the Platinum to Gold ratio's ",
             'RATIO_PLAT_SILVER_D': "the Platinum to Silver ratio's ",
             'RATIO_PLAT_COPPER_D': "the Platinum to Copper ratio's ",
             'RATIO_VDE_WTICRUDE_D': "the VDE Energy ETF to WTI Crude Oil ratio's ",  
             'RATIO_HYG_WTICRUDE_D':"the High Yield Corporate Credit to WTI Crude Oil ratio's ",
             'RATIO_HYG_GASOLINE_D':"the High Yield Corporate Credit to Gasoline ratio's ",
             'RATIO_TLT_WTICRUDE_D':"the 20+ Year Treasury Bond to WTI Crude Oil ratio's ",    
             'RATIO_IYT_DJIA_D':"the Dow Transports to Dow Industrial Average ratio's ",                                
             'RSX_D':"the VanEck Russian stock market index ETF's ",
             'ISRA_D':"the VanEck Israeli stock market index ETF's ",
             'VNM_D':"the VanEck Vietnam stock market index ETF's ",
             'PLND_D':"the VanEck Poland stock market index ETF's ",
             'LIT_D':"the GlobalX Lithium and Battery Tech ETF's ",
             'VDE_D':"the Vanguard energy sector ETF's ",  
             'EWL_D': "the MSCI iShares Switzerland ETF's ", 
             'EWI_D': "the MSCI iShares Italy ETF's ",   
             'XOP_D':"the SPDR S&P Oil & Gas Explorers ETF's ",
             'HYG_D':"the iShares High Yield Corporate Bond ETF's ",
             'EFA_D':"iShares MSCI EAFE Index Fund ETF's ", 
             'EEM_D':"iShares MSCI Emerging Markets ETF's ", 
             'TLT_D':"iShares 20+ Year Treasury Bond ETF's ",   
             'IYT_D':"iShares Dow Jones Transportation ETF's ",                                                           
            }

#NL expressions for the primary comparison field box.
NL_FIELD_LIB={
         'CLOSE':'close has been ',
         'VAISI':'VaiSi indicator has been ',
         'DATE':'date has been ',
         'DAY_OF_WEEK':'day of the week was ',
         'WEEK_OF_YEAR': 'week of the year was ',
         'MONTH_OF_YEAR': 'calendar month was ',
         'HIGH':'high has been ',
         'LOW': 'low has been ',
         'OPEN': 'open has been ',
         'MID': 'average daily trading price has been ',
         'VOLUME': 'trading volume has been ',
         '78_Period_Max_Spec_Long':'78-week high of speculator long positions has been ',
         '78_Period_Max_Spec_Shorts':'78-week high of speculator short positions has been ',
         '78_Period_Min_Spec_Long':'78-week low of speculator long positions has been ',
         '78_Period_Min_Spec_Shorts':'78-week low of speculator short positions has been ',
         'Blees_Delta': 'difference between the blees long rating and blees short rating has been ',
         'Blees_Rating_Spec_Longs':'Blees rating for spec. longs has been ',
         'Blees_Rating_Spec_Shorts':'Blees rating for spec. shorts has been ',
         'Comm_Long':'commercial long positions have been ',
         'Comm_Short':'commercial short positions have been ',
         'Delta_Open_Interest':'week-over-week change in open interest has been ',
         'Delta_Tot_Spec_Long':'week-over-week change in speculator long positions has been ',
         'Delta_Tot_Spec_Short':'week-over-week change in speculator short positions has been ',
         'Dealer_Longs': 'dealer long positions have been ',
         'Dealer_Shorts': 'dealer short positions have been ',
         'Dealer_Spreads': 'dealer spreads have been ',
         'Leveraged_Funds_Longs': 'leveraged funds long positions have been ',
         'Leveraged_Funds_Shorts': 'leveraged funds short positions have been ',
         'Leveraged_Funds_Spreads': 'leveraged funds spreads have been ',
         'Money_Manager_Longs':'money manager long positions have been ',
         'Money_Manager_Shorts':'money manager short positions have been ',
         'Money_Manager_Spreads':'money manager positional spread has been ',
         'Net_Spec_Perc_OI':'net speculator positions as a percentage of open interest have been ',
         'Non_Reportable_Longs':'non-reportable long positions have been ',
         'Non_Reportable_Shorts':'non-reportable short positions have been ',
         'Open_Interest':'open interest has been ',
         'Other_Reportable_Longs':'other reportable long positions have been ',
         'Other_Reportable_Shorts':'other reportable short positions have been ',
         'Other_Reportable_Spreads':'spread of other reportable positions has been ',
         'Producer/Merchant/Processor/User_Longs':'producer, merchant, processor, and user longs have been ',
         'Producer/Merchant/Processor/User_Shorts':'producer, merchant, processor, and user shorts have been ',
         'Small_Long':'small speculator long positions have been ',
         'Small_Short':'small speculator short positions have been ',
         'Spec_Long':'large speculator long positions have been ', 
         'Spec_Short':'large speculator short positions have been ',
         'Swap_Dealer_Longs':'swap dealer long positions have been ',
         'Swap_Dealer_Shorts':'swap dealer short positions have been ',
         'Swap_Dealer_Spreads':'the spread of swap dealer positions has been ',
         'Tot_Spec_Long': 'total speculator long positions have been ',
         'Tot_Spec_Short': 'total speculator short positions have been ',
         'Total_Reportable_Longs':'total reportable long positions have been ',
         'Total_Reportable_Shorts':'total reportable short positions have been ', 
         'Tot_Spec_Long_Perc_OI':'total speculator longs as a percentage of open interest have been ',
         'Tot_Spec_Short_Perc_OI':'total speculator shorts as a percentage of open interest have been ',
         'Delta_Open_Interest_Perc_OI':'week-over-week change in open interest as a percentage has been ',
         'Delta_Tot_Spec_Long_Perc_OI':'week-over-week change in total speculator long positions has been ',
         }            


PLOT_EXCLUSIONS=['DJIA_COT_FO',
                 'E-MINI_RUSSELL_2000_COT_FO',
                 'E-MINI_MSCI_EMERGING_MARKETS_COT_FO',]

PLOT_TITLES_LIB={
             'GOLD_D': "Gold ",
             'SILVER_D': "Silver ",
             'PALLADIUM_D': "Palladium ",
             'PLATINUM_D':"Platinum ",
             'ALUMINUM_D':"Aluminum ",
             'USD_D': "the US Dollar ",
             'SPX_D': "the S&P 500 Index ",
             'VIX_D': "the VIX ",
             'UST10Y_D':"10-Year US Treasuries ",
             'UST2Y_D':"2-Year US Treasuries ",
             'UST5Y_D':"5-Year US Treasuries ",
             'UST30Y_D':"30-Year US Treasuries ",
             'FEDFUNDS_30_D':"30-Day Fed Funds Rate ",
             'CORN_D':"Corn ",
             'DJIA_D':"the Down Jones Industrial Average ",
             'OATS_D':"Oat futures ",
             'ROUGH_RICE_D':"Rough Rice futures ",
             'SOYBEANS_D':"Soybean futures ",
             'WHEAT_D':"Wheat futures ",
             'AUD_D':"the Australian Dollar ",
             'GBP_D':"the British Pound ",
             'CAD_D':"the Canadian Dollar ",
             'EURO_FX_D':"Euro FX ",
             'EURODOLLAR_D':"Eurodollar futures ",
             'JPY_D':"the Japanese Yen ",
             'LEAN_HOGS_D':"Lean Hog futures ",
             'LIVE_CATTLE_D':"Live cattle futures ",
             'MEXICAN_PESO_D':"the Mexican Peso ",
             'NASDAQ100_D':"the Nasdaq 100 Index ",
             'NZD_D':"the New Zealand Dollar ",
             'NIKKEI225_D':"the Nikkei 225 Index ",
             'CHF_D':"the Swiss Franc ",
             'COPPER_D': "Copper ",
             'RUSSEL2000_D':"the Russell 2000 Index ",
             'RUSSEL1000_D':"the Russell 1000 Index ",
             'EURO_STOXX_50_D':"the Euro Stoxx 50 Index ",
             'COFFEE_D':"Coffee futures ",
             'COTTON_D':"Cotton futures ",
             'GASOIL_D':"Gasoil futures ",
             'HEATING_OIL_D':"Heating Oil futures ",
             'ORANGE_JUICE_D':"Orange Juice futures ",
             'SUGAR_D':"Sugar futures ",
             'NATURAL_GAS_D':"Natural Gas futures ",
             'WTI_CRUDE_OIL_D':"WTI Crude Oil futures ",
             'FTSE100_D':"the FTSE 100 Index ",
             'TSX60_D':"the TSX 60 Index ",
             'GASOLINE_D':"Gasoline futures ",
             'BITCOIN_USD_D':"Bitcoin ($USD) ",
             'ETHEREUM_USD_D':"Etherium ($USD) ",
             'US1MO_TREASURY_YIELD_D': "1-month US treasury yields ",
             'US2MO_TREASURY_YIELD_D': "2-month US treasury yields ",
             'US3MO_TREASURY_YIELD_D': "3-month US treasury yields ",
             'US6MO_TREASURY_YIELD_D': "6-month US treasury yields ",
             'US1YR_TREASURY_YIELD_D': "1-year US treasury yields ",
             'US2YR_TREASURY_YIELD_D': "2-year US treasury yields ",
             'US3YR_TREASURY_YIELD_D': "3-year US treasury yields ",
             'US5YR_TREASURY_YIELD_D': "5-year US treasury yields ",
             'US7YR_TREASURY_YIELD_D': "7-year US treasury yields ",
             'US10YR_TREASURY_YIELD_D': "10-year US treasury yields ",
             'US20YR_TREASURY_YIELD_D': "20-year US treasury yields ",
             'US30YR_TREASURY_YIELD_D': "30-year US treasury yields ",
             'US_INFLATION_YOY_D': "year-over-year US CPI inflation ",
             'US_HY_CREDIT_YIELD_D': "high yield US corporate bond yields ",
             'EM_HY_CREDIT_YIELD_D': "emerging market high yield credit yields ",
             'YC10Y5Y_D': "10-year to 5-year US treasury yield spread ",
             'YC10Y2Y_D': "10-year to 2-year US treasury yield spread ",
             'YC10Y3MO_D': "10-year to 3-month US treasury yield spread ",
             'YC5Y1Y_D': "5-year to 1-year US treasury yield spread ",
             'YC1Y1MO_D': "1-year to 1-month US treasury yield spread ",
             'US1MO_TREASURY_REAL_YIELD_D': "1-month inflation-adjusted US treasury yield ",
             'US3MO_TREASURY_REAL_YIELD_D': "3-month inflation-adjusted US treasury yield ",
             'US6MO_TREASURY_REAL_YIELD_D': "6-month inflation-adjusted US treasury yield ",
             'US1YR_TREASURY_REAL_YIELD_D': "1-year inflation-adjusted US treasury yield ",
             'US2YR_TREASURY_REAL_YIELD_D': "2-year inflation-adjusted US treasury yield ",
             'US3YR_TREASURY_REAL_YIELD_D': "3-year inflation-adjusted US treasury yield ",
             'US5YR_TREASURY_REAL_YIELD_D': "5-year inflation-adjusted US treasury yield ",
             'US7YR_TREASURY_REAL_YIELD_D': "7-year inflation-adjusted US treasury yield ",
             'US10YR_TREASURY_REAL_YIELD_D': "10-year inflation-adjusted US treasury yield ",
             'US20YR_TREASURY_REAL_YIELD_D': "20-year inflation-adjusted US treasury yield ",
             'US30YR_TREASURY_REAL_YIELD_D': "30-year inflation-adjusted US treasury yield ",
             'GDX_D':"the VanEck senior gold miners ETF (GDX) ",
             'GDXJ_D': "the VanEck junior gold miners ETF (GDXJ) ",
             'VWO_D':"the Vanguard emerging markets stock index ETF (VWO) ",
             'FXI_D':"the iShares China large cap ETF (FXI) ",  
             'PESPX_D':"the Shiller S&P 500 price to earnings ratio",
             'VCR_D':"the Vanguard consumer discretionary sector ETF (VCR) ",
             'VDC_D':"the Vanguard consumer staples sector ETF (VDC) ",
             'VPU_D':"the Vanguard electric utilities sector ETF (VPU) ",
             'XLF_D':"the SPDR financial sector ETF (XLF) ",
             'VIS_D':"the Vanguard industrial sector ETF (VIS) ",  
             'VHT_D':"the Vanguard health care sector ETF (VHT) ",
             'VNQ_D':"the Vanguard real estate sector ETF (VNQ) ", 
             'VOX_D':"the Vanguard telecommunications sector ETF (VOX) ",
             'IBB_D':"the iShares Nasdaq Biotechnology sector ETF (IBB) ",
             'SIL_D':"the GlobalX Funds Silver Miner ETF (SIL) ",               
             'CLOSE':'close ',
             'VAISI':'VaiSi ',
             'DATE':'date',
             'DAY_OF_WEEK':'day of the week ',
             'WEEK_OF_YEAR': 'week of the year ',
             'MONTH_OF_YEAR': 'calendar month ',
             'HIGH':'high ',
             'LOW': 'low ',
             'OPEN': 'open ',
             'MID': 'average daily trading price ',
             'VOLUME': 'trading volume ',
             'Asset_Manager_Shorts': 'asset manager short positions ',
             'Asset_Manager_Longs': 'asset manager long positions ',
             'Asset_Manager_Spreads': 'asset manager position spreads ',
             '78_Period_Max_Spec_Long':'78-week high of speculator long positions ',
             '78_Period_Max_Spec_Shorts':'78-week high of speculator short positions ',
             '78_Period_Min_Spec_Long':'78-week low of speculator long positions ',
             '78_Period_Min_Spec_Shorts':'78-week low of speculator short positions ',
             'Blees_Delta': 'difference between the blees long rating and blees short rating ',
             'Blees_Rating_Spec_Longs':'Blees rating for spec. longs ',
             'Blees_Rating_Spec_Shorts':'Blees rating for spec. shorts ',
             'Comm_Long':'commercial long positions ',
             'Comm_Short':'commercial short positions ',
             'Dealer_Longs': 'dealer long positions ',
             'Dealer_Shorts': 'dealer short positions ',
             'Dealer_Spreads': 'dealer spreads ',
             'Delta_Open_Interest':'week-over-week change in open interest ',
             'Delta_Tot_Spec_Long':'week-over-week change in speculator long positions ',
             'Delta_Tot_Spec_Short':'week-over-week change in speculator short positions ',
             'Leveraged_Funds_Longs': 'leveraged funds long positions ',
             'Leveraged_Funds_Shorts': 'leveraged funds short positions ',
             'Leveraged_Funds_Spreads': 'leveraged funds spreads ',
             'Money_Manager_Longs':'money manager long positions ',
             'Money_Manager_Shorts':'money manager short positions ',
             'Money_Manager_Spreads':'money manager positional spread ',
             'Net_Spec_Perc_OI':'net speculator positions as a percentage of open interest ',
             'Non_Reportable_Longs':'non-reportable long positions ',
             'Non_Reportable_Shorts':'non-reportable short positions ',
             'Open_Interest':'open interest ',
             'Other_Reportable_Longs':'other reportable long positions ',
             'Other_Reportable_Shorts':'other reportable short positions ',
             'Other_Reportable_Spreads':'spread of other reportable positions ',
             'Producer/Merchant/Processor/User_Longs':'producer, merchant, processor, and user longs ',
             'Producer/Merchant/Processor/User_Shorts':'producer, merchant, processor, and user shorts ',
             'Small_Long':'small speculator long positions ',
             'Small_Short':'small speculator short positions ',
             'Spec_Long':'large speculator long positions ', 
             'Spec_Short':'large speculator short positions ',
             'Swap_Dealer_Longs':'swap dealer long positions ',
             'Swap_Dealer_Shorts':'swap dealer short positions ',
             'Swap_Dealer_Spreads':'spread of swap dealer positions ',
             'Tot_Spec_Long': 'total speculator long positions ',
             'Tot_Spec_Short': 'total speculator short positions ',
             'Total_Reportable_Longs':'total reportable long positions ',
             'Total_Reportable_Shorts':'total reportable short positions ',
             'Tot_Spec_Long_Perc_OI':'total speculator longs as a percentage of open interest ',
             'Tot_Spec_Short_Perc_OI':'total speculator shorts as a percentage of open interest ',
             'Delta_Open_Interest_Perc_OI':'week-over-week change in open interest as a percentage ',
             'Delta_Tot_Spec_Long_Perc_OI':'week-over-week change in total speculator long positions ',
             'CANADIAN_DOLLAR_COT_FO':"Canadian Dollar committment of traders report ",
             'SILVER_COT_FO': "Silver committment of traders report ",
             'GOLD_COT_FO': "Gold committment of traders report ",
             'COPPER_COT_FO': "Copper committment of traders report ",
             'CORN_COT_FO': "Corn committment of traders report ",
             'COTTON_COT_FO':"Cotton committment of traders report ",
             'DJIA_COT_FO':"Dow Jones Industrial Average committment of traders report ",
             'E-MINI_MSCI_EMERGING_MARKETS_COT_FO':"E-mini MSCI Emerging Markets committment of traders report ",
             'E-MINI_RUSSELL_2000_COT_FO':"E-mini Russell 2000 Index committment of traders report ",
             'E-MINI_SPX_500_COT_FO':"S&P500 committment of traders report ",
             'FRZN_CONCENTRATED_ORANGE_JUICE_COT_FO':"Frozen orange juice committment of traders report ",
             '10YR_3MO_INTEREST_RATE_SWAPS_COT_FO':"10-Year / 3- Month interest rate swap committment of traders report ",
             'JAPANESE_YEN_COT_FO':"Japanese Yen committment of traders report ",
             'LIVE_CATTLE_COT_FO':"Live cattle committment of traders report ",
             'SOY_BEANS_COT_FO':"Soybeans committment of traders report ",
             'NASDAQ_100_COT_FO':"Nasdaq 100 index committment of traders report ",
             'US_TREASURY_BONDS_COT_FO':"US Treasury Bond committment of traders report ",
             'VIX_COT_FO':"VIX committment of traders report ",
             'PLATINUM_COT_FO':"Platinum committment of traders report ",
             'PALLADIUM_COT_FO':"Palladium committment of traders report ",     
             'RATIO_GOLD_SILVER_D': "the Gold-Silver Ratio ",
             'RATIO_COPPER_GOLD_D': "the Copper-Gold Ratio ",
             'RATIO_GOLD_WTI_D': "the Gold-WTI Crude Oil Ratio ",
             'RATIO_SPX_GOLD_D': "the S&P500-Gold Ratio ",
             'RATIO_GDX_GOLD_D': "the GDX-Gold Ratio ",
             'RATIO_SIL_SILVER_D': "the SIL to Silver Ratio ", 
             'RATIO_VDE_SPX_D': 'the Energy Sector to S&P500 Ratio ',
             'RATIO_GDX_SPX_D': 'the Senior Gold Mining Sector to S&P500 Ratio ',
             'RATIO_IBB_SPX_D': 'the Biotechnology Sector to S&P500 Ratio ',
             'RATIO_FXI_SPX_D': 'the Chinese Stock Index to S&P500 Ratio ',
             'RATIO_RSX_SPX_D': 'the Russia Stock Index to S&P500 Ratio ',
             'RATIO_GOLD_UST10Y_D': 'the Gold to 10-Year US treasury Ratio ',
             'RATIO_SPX_UST10Y_D': 'the S&P500 to 10-Year US treasury Ratio ',
             'RATIO_PLAT_GOLD_D': "the Platinum to Gold Ratio ",
             'RATIO_PLAT_SILVER_D': "the Platinum to Silver Ratio ",
             'RATIO_PLAT_COPPER_D': "the Platinum to Copper Ratio ",
             'RATIO_VDE_WTICRUDE_D': "the VDE Energy ETF to WTI Crude Oil Ratio ",      
             'RATIO_HYG_WTICRUDE_D':"the High Yield Corporate Credit to WTI Crude Oil ratio ",
             'RATIO_HYG_GASOLINE_D':"the High Yield Corporate Credit to Gasoline ratio ",
             'RATIO_TLT_WTICRUDE_D':"the 20+ Year Treasury Bond to WTI Crude Oil ratio ",   
             'RATIO_IYT_DJIA_D':"the Dow Transports to Dow Industrial Average ratio ",                                     
             'RSX_D':"the VanEck Russian stock market index ETF ",
             'ISRA_D':"the VanEck Israeli stock market index ETF ",
             'VNM_D':"the VanEck Vietnam stock market index ETF ",
             'PLND_D':"the VanEck Poland stock market index ETF ", 
             'LIT_D':"the GlobalX Lithium and Battery Tech ETF ",
             'VDE_D':"the Vanguard energy sector ETF ",   
             'EWL_D': "the MSCI iShares Switzerland ETF ",  
             'EWI_D': "the MSCI iShares Italy ETF",  
             'XOP_D': "the SPDR S&P Oil & Gas Explorers ETF ",
             'HYG_D': "the iShares High Yield Corporate Bond ETF ",
             'EFA_D': "iShares MSCI EAFE Index Fund ETF ",  
             'EEM_D':"iShares MSCI Emerging Markets ETF ", 
             'TLT_D':"iShares 20+ Year Treasury Bond ETF ",  
             'IYT_D':"iShares Dow Jones Transportation ETF ",                                                          
             }

#VanAurum Extremes settings:
#Extremes will scan all the assets and indicators included in both of these lists.

EXTREMES_THRESH_UPPER=97
EXTREMES_THRESH_LOWER=3
EXTREMES_ASSETS=['ALUMINUM_D',
                'AUD_D',
                'BITCOIN_USD_D',
                'CAD_D',
                'CHF_D',
                'COFFEE_D',
                'COPPER_COT_FO',
                'COPPER_D',
                'CORN_COT_FO',
                'CORN_D',
                'COTTON_COT_FO',
                'COTTON_D',
                'CANADIAN_DOLLAR_COT_FO',
                #'DJIA_COT_FO',
                'DJIA_D',
                #'E-MINI_MSCI_EMERGING_MARKETS_COT_FO',
                'E-MINI_RUSSELL_2000_COT_FO',
                'E-MINI_SPX_500_COT_FO',
                'EM_HY_CREDIT_YIELD_D',
                'ETHEREUM_USD_D',
                'EURODOLLAR_D',
                'EURO_FX_D',
                'EURO_STOXX_50_D',
                'FEDFUNDS_30_D',
                'FRZN_CONCENTRATED_ORANGE_JUICE_COT_FO',
                'FTSE100_D',
                'FXI_D',
                'GASOIL_D',
                'GASOLINE_D',
                'GBP_D',
                'GDX_D',
                'GDXJ_D',
                'GOLD_COT_FO',
                'GOLD_D',
                'HEATING_OIL_D',
                'JAPANESE_YEN_COT_FO',
                'JPY_D',
                'LEAN_HOGS_D',
                'LIVE_CATTLE_COT_FO',
                'LIVE_CATTLE_D',
                'MEXICAN_PESO_D',
                'NASDAQ100_D',
                'NASDAQ_100_COT_FO',
                'NATURAL_GAS_D',
                'NIKKEI225_D',
                'NZD_D',
                'OATS_D',
                'ORANGE_JUICE_D',
                'PALLADIUM_COT_FO',
                'PALLADIUM_D',
                'PESPX_D',
                'PLATINUM_COT_FO',
                'PLATINUM_D',
                'ROUGH_RICE_D',
                'RUSSEL1000_D',
                'RUSSEL2000_D',
                'SILVER_COT_FO',
                'SILVER_D',
                'SOYBEANS_D',
                'SOY_BEANS_COT_FO',
                'SPX_D',
                'SUGAR_D',
                'TSX60_D',
                'US10YR_TREASURY_REAL_YIELD_D',
                'US10YR_TREASURY_YIELD_D',
                'US1MO_TREASURY_REAL_YIELD_D',
                'US1MO_TREASURY_YIELD_D',
                #'US2MO_TREASURY_YIELD_D',
                'US1YR_TREASURY_REAL_YIELD_D',
                'US1YR_TREASURY_YIELD_D',
                'US20YR_TREASURY_REAL_YIELD_D',
                'US20YR_TREASURY_YIELD_D',
                'US2YR_TREASURY_REAL_YIELD_D',
                'US2YR_TREASURY_YIELD_D',
                'US30YR_TREASURY_REAL_YIELD_D',
                'US30YR_TREASURY_YIELD_D',
                'US3MO_TREASURY_REAL_YIELD_D',
                'US3MO_TREASURY_YIELD_D',
                'US3YR_TREASURY_REAL_YIELD_D',
                'US3YR_TREASURY_YIELD_D',
                'US5YR_TREASURY_REAL_YIELD_D',
                'US5YR_TREASURY_YIELD_D',
                'US6MO_TREASURY_REAL_YIELD_D',
                'US6MO_TREASURY_YIELD_D',
                'US7YR_TREASURY_REAL_YIELD_D',
                'US7YR_TREASURY_YIELD_D',
                'USD_D',
                'UST10Y_D',
                'UST2Y_D',
                'UST30Y_D',
                'UST5Y_D',
                'US_HY_CREDIT_YIELD_D',
                'US_TREASURY_BONDS_COT_FO',
                'VIX_COT_FO',
                'VIX_D',
                'VWO_D',
                'WHEAT_D',
                'WTI_CRUDE_OIL_D',
                'YC10Y2Y_D',
                'YC10Y3MO_D',
                'YC10Y5Y_D',
                'YC1Y1MO_D',
                'YC5Y1Y_D',
                'VCR_D',
                'VDC_D',
                'VPU_D',
                'XLF_D',
                'VIS_D',  
                'VHT_D',
                'VNQ_D', 
                'VOX_D',
                'IBB_D',  
                'SIL_D',
                'RATIO_GOLD_SILVER_D',
                'RATIO_COPPER_GOLD_D',
                'RATIO_GOLD_WTI_D',
                'RATIO_SPX_GOLD_D',
                'RATIO_GDX_GOLD_D',
                'RATIO_SIL_SILVER_D',
                'RATIO_VDE_SPX_D',
                'RATIO_GDX_SPX_D',
                'RATIO_IBB_SPX_D',
                'RATIO_FXI_SPX_D',
                'RATIO_RSX_SPX_D',
                'RATIO_GOLD_UST10Y_D',
                'RATIO_SPX_UST10Y_D',      
                'RATIO_PLAT_GOLD_D',
                'RATIO_PLAT_SILVER_D',
                'RATIO_PLAT_COPPER_D',
                'RATIO_VDE_WTICRUDE_D',    
                'RATIO_HYG_WTICRUDE_D',
                'RATIO_HYG_GASOLINE_D',
                'RATIO_TLT_WTICRUDE_D',    
                'RATIO_IYT_DJIA_D',                                  
                'RSX_D',
                'ISRA_D',
                'VNM_D',
                'PLND_D',
                'LIT_D',
                'VDE_D',    
                'EWL_D',  
                'EWI_D',  
                'HYG_D',
                'XOP_D',
                'EFA_D',   
                'EEM_D',      
                'TLT_D',          
                'IYT_D',           
             ]

EXTREMES_INDICATORS=['VAISI',
                     'RSI',
                     'DMA',
                     'ROC',
                     'SLOWSTOCH',
                     'UPDOWNSUM',
                     'PROXTOBOLL',
                     'BOPMA',
                     'CLOSE',#Just added, remove it if issues arise.
                     'Open_Interest',
                     'Producer/Merchant/Processor/User_Longs',
                     'Producer/Merchant/Processor/User_Shorts',
                     'Swap_Dealer_Longs',
                     'Swap_Dealer_Shorts',
                     'Swap_Dealer_Spreads',
                     'Money_Manager_Longs',
                     'Money_Manager_Shorts',
                     'Money_Manager_Spreads',
                     'Other_Reportable_Longs',
                     'Other_Reportable_Shorts',
                     'Other_Reportable_Spreads',
                     'Total_Reportable_Longs',
                     'Total_Reportable_Shorts',
                     'Non_Reportable_Longs',
                     'Non_Reportable_Shorts',
                     'Spec_Long',
                     'Spec_Short',
                     'Tot_Spec_Long',
                     'Tot_Spec_Short',
                     'Comm_Long',
                     'Comm_Short',
                     'Small_Long',
                     'Small_Short',
                     'Net_Spec_Perc_OI',
                     'Delta_Open_Interest',
                     'Delta_Tot_Spec_Long',
                     'Delta_Tot_Spec_Short',
                     'Blees_Rating_Spec_Shorts',
                     'Blees_Rating_Spec_Longs',
                     'Blees_Delta',
                     'Tot_Spec_Long_Perc_OI',
                     'Tot_Spec_Short_Perc_OI',
                     'Delta_Open_Interest_Perc_OI',
                     'Delta_Tot_Spec_Long_Perc_OI',                     
                     ]

EXTREMES_EXCLUSIONS=[
    'SLOWSTOCHS1',
    'SLOWSTOCHS5',
    'SLOWSTOCHS10',
    'SLOWSTOCHS15',
    'SLOWSTOCHS20',
    'SLOWSTOCHS25',
    'UPDOWNSUM5',
    'UPDOWNSUM10',
    'UPDOWNSUM15',
    'UPDOWNSUM20',
    'UPDOWNSUM25',
    'UPDOWNSUM30',
    'UPDOWNSUM35',
    'UPDOWNSUM40',
    'PROXTOBOLL5',
    'PROXTOBOLL10',
    'PROXTOBOLL15',
    'PROXTOBOLL20',
    'BOPMA1',
    'BOPMA2',
    'CLOSE',
]

EXTREMES_ORDER_OF_IMPORTANCE=['DMA',
                              'PROXTOBOLL',
                              'VAISI',
                              'RSI',
                              'ROC']


#Documentation Page Asset and Indicator Master List:
###This dictionary is accesses when the asset list on the documentation page gets updated.
###Accessed by model in app Report.

ASSET_MASTER_LIST=[
             {
                 'asset':'CORN_D',
                 'asset_type': 'Commodity',
                 'description': 'Continuous futures contract price for Corn',
             },  
             {
                 'asset':'GOLD_D',
                 'asset_type': 'Commodity',
                 'description': 'Continuous futures contract price for Gold',
             },
             {
                 'asset':'SILVER_D',
                 'asset_type': 'Commodity',
                 'description': 'Continuous futures contract price for Silver',
             },                     
             {
                 'asset':'PALLADIUM_D',
                 'asset_type': 'Commodity',
                 'description': 'Continuous futures contract price for Palladium',
             }, 
             {
                 'asset':'PLATINUM_D',
                 'asset_type': 'Commodity',
                 'description': 'Continuous futures contract price for Platinum',
             },                  
             {
                 'asset':'ALUMINUM_D',
                 'asset_type': 'Commodity',
                 'description': 'Continuous futures contract price for Aluminum',
             },        
             {
                 'asset':'USD_D',
                 'asset_type': 'Currency',
                 'description': 'Continuous futures contract price for the US Dollar',
             },        
             {
                 'asset':'SPX_D',
                 'asset_type': 'Index',
                 'description': 'Continuous futures contract price for the S&P 500',
             },        
             {
                 'asset':'VIX_D',
                 'asset_type': 'Index',
                 'description': 'Continuous futures contract price for the Volatility Index (VIX)',
             },        
             {
                 'asset':'UST10Y_D',
                 'asset_type': 'Treasuries',
                 'description': 'Continuous futures contract price for the 10-Year US Treasury Bond',
             },        
             {
                 'asset':'UST2Y_D',
                 'asset_type': 'Treasuries',
                 'description': 'Continuous futures contract price for the 2-Year US Treasury Bond',
             },    
             {
                 'asset':'UST5Y_D',
                 'asset_type': 'Treasuries',
                 'description': 'Continuous futures contract price for the 5-Year US Treasury Bond',
             }, 
             {
                 'asset':'UST30Y_D',
                 'asset_type': 'Treasuries',
                 'description': 'Continuous futures contract price for the 30-Year US Treasury Bond',
             },                    
             {
                 'asset':'FEDFUNDS_30_D',
                 'asset_type': 'Economic Data',
                 'description': 'the 30-Day Federal Reserve Funds Rate',
             },    
             {
                 'asset':'DJIA_D',
                 'asset_type': 'Index',
                 'description': 'Continuous futures contract price for the Dow Jones Industrial Average',
             },   
             {
                 'asset':'OATS_D',
                 'asset_type': 'Commodity',
                 'description': 'Continuous futures contract price for the Dow Jones Industrial Average',
             },   
             {
                 'asset':'ROUGH_RICE_D',
                 'asset_type': 'Commodity',
                 'description': 'Continuous futures contract price for rough rice',
             },   
             {
                 'asset':'SOYBEANS_D',
                 'asset_type': 'Commodity',
                 'description': 'Continuous futures contract price for soybeans',
             },   
             {
                 'asset':'WHEAT_D',
                 'asset_type': 'Commodity',
                 'description': 'Continuous futures contract price for wheat',
             },   
             {
                 'asset':'AUD_D',
                 'asset_type': 'Currency',
                 'description': 'Continuous futures contract price for the Australian Dollar',
             },   
             {
                 'asset':'GBP_D',
                 'asset_type': 'Currency',
                 'description': 'Continuous futures contract price for the British Pound',
             },   
             {
                 'asset':'CAD_D',
                 'asset_type': 'Currency',
                 'description': 'Continuous futures contract price for the Canadian Dollar',
             },   
             {
                 'asset':'EURO_FX_D',
                 'asset_type': 'Currency',
                 'description': 'Continuous contract price for Euro FX Futures',
             },   
             {
                 'asset':'EURODOLLAR_D',
                 'asset_type': 'Currency',
                 'description': 'Continuous contract price for Eurodollar futures',
             }, 
             {
                 'asset':'JPY_D',
                 'asset_type': 'Currency',
                 'description': 'Continuous contract price for Japanese Yen futures',
             }, 
             {
                 'asset':'LEAN_HOGS_D',
                 'asset_type': 'Commodity',
                 'description': 'Continuous contract price for lean hog futures',
             }, 
             {
                 'asset':'LIVE_CATTLE_D',
                 'asset_type': 'Commodity',
                 'description': 'Continuous contract price for live cattle futures',
             }, 
             {
                 'asset':'MEXICAN_PESO_D',
                 'asset_type': 'Currency',
                 'description': 'Continuous contract price for the Mexican Peso',
             }, 
             {
                 'asset':'NASDAQ100_D',
                 'asset_type': 'Index',
                 'description': 'Continuous contract price for Nasdaq 100 futures',
             }, 
             {
                 'asset':'NZD_D',
                 'asset_type': 'Currency',
                 'description': 'Continuous contract price for New Zealand Dollar futures',
             }, 
             {
                 'asset':'NIKKEI225_D',
                 'asset_type': 'Index',
                 'description': 'Continuous contract price for Nikkei 225 index futures',
             }, 
             {
                 'asset':'CHF_D',
                 'asset_type': 'Currency',
                 'description': 'Continuous contract price for Swiss Franc futures',
             }, 
             {
                 'asset':'COPPER_D',
                 'asset_type': 'Commodity',
                 'description': 'Continuous contract price for copper futures',
             }, 
             {
                 'asset':'RUSSEL2000_D',
                 'asset_type': 'Index',
                 'description': 'Continuous contract price for Russel 2000 index futures',
             }, 
             {
                 'asset':'RUSSEL1000_D',
                 'asset_type': 'Index',
                 'description': 'Continuous contract price for Russel 1000 index futures',
             }, 
             {
                 'asset':'EURO_STOXX_50_D',
                 'asset_type': 'Index',
                 'description': 'Continuous contract price for Euro Stoxx 50 index futures',
             }, 
             {
                 'asset':'COFFEE_D',
                 'asset_type': 'Commodity',
                 'description': 'Continuous contract price for coffee futures',
             }, 
             {
                 'asset':'COTTON_D',
                 'asset_type': 'Commodity',
                 'description': 'Continuous contract price for cotton futures',
             }, 
             {
                 'asset':'GASOIL_D',
                 'asset_type': 'Commodity',
                 'description': 'Continuous contract price for gas oil futures',
             }, 
             {
                 'asset':'HEATING_OIL_D',
                 'asset_type': 'Commodity',
                 'description': 'Continuous contract price for heating oil futures',
             }, 
             {
                 'asset':'ORANGE_JUICE_D',
                 'asset_type': 'Commodity',
                 'description': 'Continuous contract price for orange juice futures',
             }, 
             {
                 'asset':'SUGAR_D',
                 'asset_type': 'Commodity',
                 'description': 'Continuous contract price for sugar futures',
             }, 
             {
                 'asset':'NATURAL_GAS_D',
                 'asset_type': 'Commodity',
                 'description': 'Continuous contract price for natural gas futures',
             }, 
             {
                 'asset':'WTI_CRUDE_OIL_D',
                 'asset_type': 'Commodity',
                 'description': 'Continuous contract price for WTI Crude Oil futures',
             }, 
             {
                 'asset':'FTSE100_D',
                 'asset_type': 'Index',
                 'description': 'Continuous contract price for FTSE 100 futures',
             }, 
             {
                 'asset':'TSX60_D',
                 'asset_type': 'Index',
                 'description': 'Continuous contract price for TSX 60 futures',
             }, 
             {
                 'asset':'GASOLINE_D',
                 'asset_type': 'Commodity',
                 'description': 'Continuous contract price for gasoline futures',
             }, 
             {
                 'asset':'BITCOIN_D',
                 'asset_type': 'Cryptocurrency',
                 'description': 'Mid pricing levels for continuous Bitcoin prices',
             }, 
             {
                 'asset':'ETHEREUM_D',
                 'asset_type': 'Cryptocurrency',
                 'description': 'Mid pricing levels for continuous Ethereum prices',
             }, 
             {
                 'asset':'US1MO_TREASURY_YIELD_D',
                 'asset_type': 'Interest Rate',
                 'description': 'Prevailing yields on 1-month US Treasuries',
             }, 
             {
                 'asset':'US2MO_TREASURY_YIELD_D',
                 'asset_type': 'Interest Rate',
                 'description': 'Prevailing yields on 2-month US Treasuries',
             }, 
             {
                 'asset':'US3MO_TREASURY_YIELD_D',
                 'asset_type': 'Interest Rate',
                 'description': 'Prevailing yields on 3-month US Treasuries',
             }, 
             {
                 'asset':'US6MO_TREASURY_YIELD_D',
                 'asset_type': 'Interest Rate',
                 'description': 'Prevailing yields on 6-month US Treasuries',
             }, 
             {
                 'asset':'US1YR_TREASURY_YIELD_D',
                 'asset_type': 'Interest Rate',
                 'description': 'Prevailing yields on 1-year US Treasuries',
             }, 
             {
                 'asset':'US2YR_TREASURY_YIELD_D',
                 'asset_type': 'Interest Rate',
                 'description': 'Prevailing yields on 2-year US Treasuries',
             }, 
             {
                 'asset':'US3YR_TREASURY_YIELD_D',
                 'asset_type': 'Interest Rate',
                 'description': 'Prevailing yields on 3-year US Treasuries',
             }, 
             {
                 'asset':'US5YR_TREASURY_YIELD_D',
                 'asset_type': 'Interest Rate',
                 'description': 'Prevailing yields on 5-year US Treasuries',
             }, 
             {
                 'asset':'US7YR_TREASURY_YIELD_D',
                 'asset_type': 'Interest Rate',
                 'description': 'Prevailing yields on 7-year US Treasuries',
             }, 
             {
                 'asset':'US10YR_TREASURY_YIELD_D',
                 'asset_type': 'Interest Rate',
                 'description': 'Prevailing yields on 10-year US Treasuries',
             }, 
             {
                 'asset':'US20YR_TREASURY_YIELD_D',
                 'asset_type': 'Interest Rate',
                 'description': 'Prevailing yields on 20-year US Treasuries',
             }, 
             {
                 'asset':'US30YR_TREASURY_YIELD_D',
                 'asset_type': 'Interest Rate',
                 'description': 'Prevailing yields on 30-year US Treasuries',
             }, 
             {
                 'asset':'US_INFLATION_YOY_D',
                 'asset_type': 'Economic Data',
                 'description': 'Year-over-year US CPI inflation data',
             }, 
             {
                 'asset':'US_HY_CREDIT_YIELD_D',
                 'asset_type': 'Interest Rate',
                 'description': 'high yield US corporate bond yields',
             },
             {
                 'asset':'EM_HY_CREDIT_YIELD_D',
                 'asset_type': 'Interest Rate',
                 'description': 'emerging market high yield corporate bond yields',
             },
             {
                 'asset':'YC10Y5Y_D',
                 'asset_type': 'Yield Curve',
                 'description': 'Spread between US 10-Year and 5-Year treasury bond yields',
             },
             {
                 'asset':'YC10Y2Y_D',
                 'asset_type': 'Yield Curve',
                 'description': 'Spread between US 10-Year and 2-Year treasury bond yields',
             },
             {
                 'asset':'YC10Y3MO_D',
                 'asset_type': 'Yield Curve',
                 'description': 'Spread between US 10-Year and 3-month treasury bond yields',
             },
             {
                 'asset':'YC5Y1Y_D',
                 'asset_type': 'Yield Curve',
                 'description': 'Spread between US 5-Year and 1-year treasury bond yields',
             },
             {
                 'asset':'YC1Y1MO_D',
                 'asset_type': 'Yield Curve',
                 'description': 'Spread between US 1-Year and 1-month treasury bond yields',
             },
             {
                 'asset':'US1MO_TREASURY_REAL_YIELD_D',
                 'asset_type': 'Interest Rate',
                 'description': 'the 1-month inflation-adjusted US treasury yield',
             },
             {
                 'asset':'US3MO_TREASURY_REAL_YIELD_D',
                 'asset_type': 'Interest Rate',
                 'description': 'the 3-month inflation-adjusted US treasury yield',
             },
             {
                 'asset':'US6MO_TREASURY_REAL_YIELD_D',
                 'asset_type': 'Interest Rate',
                 'description': 'the 6-month inflation-adjusted US treasury yield',
             },
             {
                 'asset':'US1YR_TREASURY_REAL_YIELD_D',
                 'asset_type': 'Interest Rate',
                 'description': 'the 1-year inflation-adjusted US treasury yield',
             },
             {
                 'asset':'US2YR_TREASURY_REAL_YIELD_D',
                 'asset_type': 'Interest Rate',
                 'description': 'the 2-year inflation-adjusted US treasury yield',
             },
             {
                 'asset':'US3YR_TREASURY_REAL_YIELD_D',
                 'asset_type': 'Interest Rate',
                 'description': 'the 3-year inflation-adjusted US treasury yield',
             },
             {
                 'asset':'US5YR_TREASURY_REAL_YIELD_D',
                 'asset_type': 'Interest Rate',
                 'description': 'the 5-year inflation-adjusted US treasury yield',
             },
             {
                 'asset':'US7YR_TREASURY_REAL_YIELD_D',
                 'asset_type': 'Interest Rate',
                 'description': 'the 7-year inflation-adjusted US treasury yield',
             },
             {
                 'asset':'US10YR_TREASURY_REAL_YIELD_D',
                 'asset_type': 'Interest Rate',
                 'description': 'the 10-year inflation-adjusted US treasury yield',
             },
             {
                 'asset':'US20YR_TREASURY_REAL_YIELD_D',
                 'asset_type': 'Interest Rate',
                 'description': 'the 20-year inflation-adjusted US treasury yield',
             },
             {
                 'asset':'US30YR_TREASURY_REAL_YIELD_D',
                 'asset_type': 'Interest Rate',
                 'description': 'the 30-year inflation-adjusted US treasury yield',
             },
             {
                 'asset':'GDX_D',
                 'asset_type': 'Sector ETF',
                 'description': 'the VanEck senior gold miners ETF',
             },
             {
                 'asset':'GDXJ_D',
                 'asset_type': 'Sector ETF',
                 'description': 'the VanEck junior gold miners ETF',
             },             
             {
                 'asset':'VWO_D',
                 'asset_type': 'Sector ETF',
                 'description': 'the Vanguard emerging markets stock index ETF',
             },           
             {
                 'asset':'FXI_D',
                 'asset_type': 'Sector ETF',
                 'description': 'the iShares China large cap stock index ETF',
             },      
             {
                 'asset':'VCR_D',
                 'asset_type': 'Sector ETF',
                 'description': 'the Vanguard consumer discretionary sector ETF',
             },      
             {
                 'asset':'VDC_D',
                 'asset_type': 'Sector ETF',
                 'description': 'the Vanguard consumer staples sector ETF',
             },    
             {
                 'asset':'VPU_D',
                 'asset_type': 'Sector ETF',
                 'description': 'the Vanguard electric utilities sector ETF',
             },    
             {
                 'asset':'XLF_D',
                 'asset_type': 'Sector ETF',
                 'description': 'the SPDR financial sector ETF',
             },    
             {
                 'asset':'VIS_D',
                 'asset_type': 'Sector ETF',
                 'description': 'the Vanguard industrial sector ETF',
             },   
             {
                 'asset':'VHT_D',
                 'asset_type': 'Sector ETF',
                 'description': 'the Vanguard health care sector ETF',
             }, 
             {
                 'asset':'VNQ_D',
                 'asset_type': 'Sector ETF',
                 'description': 'the Vanguard real estate sector ETF',
             },  
             {
                 'asset':'VOX_D',
                 'asset_type': 'Sector ETF',
                 'description': 'the Vanguard telecommunications sector ETF',
             },  
             {
                 'asset':'IBB_D',
                 'asset_type': 'Sector ETF',
                 'description': 'the iShares Nasdaq Biotechnology sector ETF',
             },  
             {
                 'asset':'SIL_D',
                 'asset_type': 'Sector ETF',
                 'description': 'the GlobalX Funds Silver Miner ETF',
             },  
             {
                 'asset':'RATIO_GOLD_SILVER_D',
                 'asset_type': 'Ratio',
                 'description': 'The gold-to-silver price ratio',
             },  
             {
                 'asset':'RATIO_COPPER_GOLD_D',
                 'asset_type': 'Ratio',
                 'description': 'The copper-to-gold price ratio',
             },  
             {
                 'asset':'RATIO_GOLD_WTI_D',
                 'asset_type': 'Ratio',
                 'description': 'The gold-to-WTI crude oil price ratio',
             },  
             {
                 'asset':'RATIO_SPX_GOLD_D',
                 'asset_type': 'Ratio',
                 'description': 'The S&P500-to-gold price ratio',
             },  
             {
                 'asset':'RATIO_GDX_GOLD_D',
                 'asset_type': 'Ratio',
                 'description': 'The GDX-to-Gold price ratio',
             },  
             {
                 'asset':'RATIO_SIL_SILVER_D',
                 'asset_type': 'Ratio',
                 'description': 'The Silver miners to Silver price ratio',
             }, 
             {
                 'asset':'SILVER_COT_FO',
                 'asset_type': 'Committment of Traders',
                 'description': 'CFTC trader positioning analytics for Silver',
             }, 
             {
                 'asset':'GOLD_COT_FO',
                 'asset_type': 'Committment of Traders',
                 'description': 'CFTC trader positioning analytics for Gold',
             },
             {
                 'asset':'COPPER_COT_FO',
                 'asset_type': 'Committment of Traders',
                 'description': 'CFTC trader positioning analytics for Copper',
             },  
             {
                 'asset':'CORN_COT_FO',
                 'asset_type': 'Committment of Traders',
                 'description': 'CFTC trader positioning analytics for Corn',
             }, 
             {
                 'asset':'COTTON_COT_FO',
                 'asset_type': 'Committment of Traders',
                 'description': 'CFTC trader positioning analytics for Cotton',
             }, 
             {
                 'asset':'E-MINI_RUSSELL_2000_COT_FO',
                 'asset_type': 'Committment of Traders',
                 'description': 'CFTC trader positioning analytics for the MSCI Russell 2000 E-mini contract',
             },  
             {
                 'asset':'E-MINI_SPX_500_COT_FO',
                 'asset_type': 'Committment of Traders',
                 'description': 'CFTC trader positioning analytics for the S&P500 E-mini contract',
             },
             {
                 'asset':'FRZN_CONCENTRATED_ORANGE_JUICE_COT_FO',
                 'asset_type': 'Committment of Traders',
                 'description': 'CFTC trader positioning analytics for frozen orange juice futures contracts',
             },
             {
                 'asset':'JAPANESE_YEN_COT_FO',
                 'asset_type': 'Committment of Traders',
                 'description': 'CFTC trader positioning analytics for japenese yen futures contracts',
             },
             {
                 'asset':'LIVE_CATTLE_COT_FO',
                 'asset_type': 'Committment of Traders',
                 'description': 'CFTC trader positioning analytics for live cattle futures contracts',
             },
             {
                 'asset':'SOY_BEANS_COT_FO',
                 'asset_type': 'Committment of Traders',
                 'description': 'CFTC trader positioning analytics for soy bean futures contracts',
             }, 
             {
                 'asset':'NASDAQ_100_COT_FO',
                 'asset_type': 'Committment of Traders',
                 'description': 'CFTC trader positioning analytics for Nasdaq 100 futures contracts',
             },
             {
                 'asset':'US_TREASURY_BONDS_COT_FO',
                 'asset_type': 'Committment of Traders',
                 'description': 'CFTC trader positioning analytics for US Treasury Bonds',
             },
             {
                 'asset':'VIX_COT_FO',
                 'asset_type': 'Committment of Traders',
                 'description': 'CFTC trader positioning analytics for VIX futures',
             },  
             {
                 'asset':'PLATINUM_COT_FO',
                 'asset_type': 'Committment of Traders',
                 'description': 'CFTC trader positioning analytics for Platinum futures',
             }, 
             {
                 'asset':'PALLADIUM_COT_FO',
                 'asset_type': 'Committment of Traders',
                 'description': 'CFTC trader positioning analytics for Palladium futures',
             },
             {
                 'asset':'RSX_D',
                 'asset_type': 'Sector ETF',
                 'description': 'VanEck Russian stock market index ETF',
             },    
             {
                 'asset':'VNM_D',
                 'asset_type': 'Sector ETF',
                 'description': 'VanEck Vietnam stock market index ETF',
             },    
             {
                 'asset':'PLND_D',
                 'asset_type': 'Sector ETF',
                 'description': 'VanEck Poland stock market index ETF',
             },           
             {
                 'asset':'ISRA_D',
                 'asset_type': 'Sector ETF',
                 'description': 'VanEck Israel stock market index ETF',
             },
             {
                 'asset':'LIT_D',
                 'asset_type': 'Sector ETF',
                 'description': 'GlobalX Lithium and Battery Technology Stock ETF',
             },
             {
                 'asset':'VDE_D',
                 'asset_type': 'Sector ETF',
                 'description': 'Vanguard Energy Sector ETF',
             },
             {
                 'asset':'EWL_D',
                 'asset_type': 'Sector ETF',
                 'description': 'MSCI iShares Switzerland ETF',
             },  
             {
                 'asset':'EWI_D',
                 'asset_type': 'Sector ETF',
                 'description': 'MSCI iShares Italy ETF',
             },                             
             {
                 'asset':'RATIO_VDE_SPX_D',
                 'asset_type': 'Ratio',
                 'description': 'The ratio of the Vanguard Energy Sector ETF to S&P500 ratio.',
             },    
             {
                 'asset':'RATIO_GDX_SPX_D',
                 'asset_type': 'Ratio',
                 'description': 'The ratio of the VanEck Senior Gold Miner ETF to S&P500 ratio.',
             }, 
             {
                 'asset':'RATIO_IBB_SPX_D',
                 'asset_type': 'Ratio',
                 'description': 'The ratio of the Biotechnology Sector ETF to S&P500 ratio.',
             },   
             {
                 'asset':'RATIO_FXI_SPX_D',
                 'asset_type': 'Ratio',
                 'description': 'The ratio of the Chinese Large Cap Stock ETF to S&P500 ratio.',
             },    
             {
                 'asset':'RATIO_RSX_SPX_D',
                 'asset_type': 'Ratio',
                 'description': 'The ratio of the Russian Large Cap Stock ETF to S&P500 ratio.',
             }, 
             {
                 'asset':'RATIO_GOLD_UST10Y_D',
                 'asset_type': 'Ratio',
                 'description': 'The ratio of Gold to 10-Year US Treasury Bonds.',
             },     
             {
                 'asset':'RATIO_SPX_UST10Y_D', 
                 'asset_type': 'Ratio',
                 'description': 'The ratio of the S&P500 to 10-Year US Treasury Bonds.',
             },  
             {
                 'asset':'RATIO_PLAT_GOLD_D', 
                 'asset_type': 'Ratio',
                 'description': 'The ratio of Platinum to Gold.',
             }, 
             {
                 'asset':'RATIO_PLAT_SILVER_D', 
                 'asset_type': 'Ratio',
                 'description': 'The ratio of Platinum to Silver.',
             },  
             {
                 'asset':'RATIO_PLAT_COPPER_D', 
                 'asset_type': 'Ratio',
                 'description': 'The ratio of Platinum to Copper.',
             },    
             {
                 'asset':'RATIO_VDE_WTICRUDE_D',
                 'asset_type': 'Ratio',
                 'description': 'The ratio of the VDE Energy ETF to WTI Crude Oil.',
             }, 
             {
                 'asset':'RATIO_HYG_WTICRUDE_D',
                 'asset_type': 'Ratio',
                 'description': 'The ratio of the HYG High Yield Corporate Credit ETF to WTI Crude Oil.',
             }, 
             {
                 'asset':'RATIO_HYG_GASOLINE_D',
                 'asset_type': 'Ratio',
                 'description': 'The ratio of the HYG High Yield Corporate Credit ETF to Gasoline.',
             }, 
             {
                 'asset':'RATIO_TLT_WTICRUDE_D',
                 'asset_type': 'Ratio',
                 'description': 'The ratio of the TLT 20+ Year Treasury Bond ETF to WTI Crude Oil.',
             },  
             {
                 'asset':'RATIO_IYT_DJIA_D',
                 'asset_type': 'Ratio',
                 'description': 'The ratio of the IYT iShares Dow Transportation ETF to DJIA.',
             },                                                            
             {
                 'asset':'HYG_D',
                 'asset_type': 'Sector ETF',
                 'description': 'iShares High Yield Corporate Bond ETF',
             }, 
             {
                 'asset':'XOP_D',
                 'asset_type': 'Sector ETF',
                 'description': 'SPDR S&P Oil & Gas Explorers and Producers ETF',
             },  
             {
                 'asset':'EFA_D',
                 'asset_type': 'Sector ETF',
                 'description': 'iShares MSCI EAFE Index Fund ETF',
             }, 
             {
                 'asset':'EEM_D',
                 'asset_type': 'Sector ETF',
                 'description': 'iShares Emerging Markets Index Fund ETF',
             },    
             {
                 'asset':'TLT_D',
                 'asset_type': 'Sector ETF',
                 'description': 'iShares 20+ Year Treasury Bond ETF',
             },   
             {
                 'asset':'IYT_D',
                 'asset_type': 'Sector ETF',
                 'description': 'iShares Dow Transportation ETF',
             },                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
]


                
REMOVED_ASSETS=[
             {
                 'asset':'DJIA_COT_FO',
                 'asset_type': 'Committment of Traders',
                 'description': 'CFTC trader positioning analytics for the Dow Jones Industrial Average',
             }, 
             {
                 'asset':'E-MINI_MSCI_EMERGING_MARKETS_COT_FO',
                 'asset_type': 'Committment of Traders',
                 'description': 'CFTC trader positioning analytics for the MSCI Emerging Markets E-mini contract',
             }, 
]                